apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.22.1
          ports:
            - containerPort: 8000
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          # Using vllm for GPU memory management
          # resources:
          #   limits:
          #     nvidia.com/gpu: 1
          volumeMounts:
            - name: vllm-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: vllm-cache
          hostPath:
            path: /opt/vllm-data
            type: DirectoryOrCreate
