apiVersion: v1
kind: Service
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  selector:
    app: open-webui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: ollama
      port: 11434
      targetPort: 11434
  type: ClusterIP
