apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  template:
    spec:
      containers:
        - name: litellm
          env:
            - name: GENERIC_CLIENT_ID
              value: ""