apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samwise

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: open-webui