apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  selector:
    matchLabels:
      app: cyberdyne02-qwen-embed-vllm
  template:
    metadata:
      labels:
        app: cyberdyne02-qwen-embed-vllm
    spec:
      # stop k8s from injecting env vars that cause vllm to fail
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: cyberdyne02.library.ucdavis.edu
      tolerations:
        - key: dedicated
          operator: Equal
          value: gpu-inference
          effect: NoSchedule
      containers:
        - name: vllm
          ports:
            - $patch: replace
            - containerPort: 8001
          args:
            - --model
            - Qwen/Qwen3-Embedding-8B
            - --host
            - "0.0.0.0"
            - --port
            - "8001"
            - --gpu-memory-utilization
            - "0.20"
            - --max-model-len
            - "8192"