apiVersion: v1
kind: Service
metadata:
  name: vllm
spec:
  selector:
    app: cyberdyne02-qwen36-vllm
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30805
