services:
  ollama:
    image: ollama/ollama:latest
    ports:
      11434:11434
    gpus: all
    environment:
      OLLAMA_HOST: 0.0.0.0:11434
      NVIDIA_VISIBLE_DEVICES: all
      OLLAMA_NUM_THREAD: 10
      OLLAMA_NUM_GPU: 999
    restart: unless-stopped
    volumes:
      - /opt/ollama-data:/root/.ollama