apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samwise

# labels:
#   app.kubernetes.io/part-of: samwise
#   environment: prod

resources:
  - ../../base

patches:
  - path: statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: postgres