apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samwise
namePrefix: cyberdyne01-qwen36-

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: vllm
  - path: service-patch.yaml
    target:
      kind: Service
      name: vllm
